import { useState, useEffect, useCallback } from "react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Legend } from "recharts";
import { ThemeToggle } from "./useTheme.jsx";

// ============================================================
// DATA LOADING — reads from viz_data.json generated by Python pipeline
// ============================================================

const FALLBACK_DATA = { matches: [], tropeDistribution: [], timeline: [], calibration: { echoScores: [], legitimateScores: [] }, legitimateExamples: [], metadata: { thresholds: { high: 0.85, medium: 0.70, low: 0.55 }, tropeNames: {}, tropeColors: {} } };

function useVizData() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch("/viz_data.json")
      .then(r => { if (!r.ok) throw new Error(`${r.status}`); return r.json(); })
      .then(d => { setData(d); setLoading(false); })
      .catch(e => {
        console.warn("viz_data.json not found, using sample data. Run: python generate_viz_data.py --generate");
        setData(null);
        setLoading(false);
        setError(e.message);
      });
  }, []);

  return { data, loading, error };
}

// ============================================================
// SAMPLE DATA — used when viz_data.json hasn't been generated yet
// ============================================================

const SAMPLE_MATCHES = [
  { id: 1, sovietText: "The main posits of modern Zionism are militant chauvinism, racism, anti-Communism and anti-Sovietism.", sovietSource: "Great Soviet Encyclopedia", sovietYear: 1975, modernText: "Zionism is a racist, settler-colonial ideology that promotes Jewish supremacy over indigenous Palestinians.", modernSource: "Campus BDS Resolution", modernYear: 2024, similarity: 0.91, tropes: ["ZIONISM_RACISM", "ZIONISM_IMPERIALISM"], confidence: "high" },
  { id: 2, sovietText: "Absurd are attempts of Zionist ideologists to present those who criticize them as antisemitic.", sovietSource: "Anti-Zionist Committee Declaration, Pravda", sovietYear: 1983, modernText: "Accusations of antisemitism are weaponized to silence legitimate criticism of Israel's apartheid regime.", modernSource: "Social Media Post", modernYear: 2024, similarity: 0.88, tropes: ["WEAPONIZED_ANTISEMITISM"], confidence: "high" },
  { id: 3, sovietText: "International Zionist Organization influences or controls significant part of media agencies and outlets in the West.", sovietSource: "Great Soviet Encyclopedia", sovietYear: 1975, modernText: "The Zionist lobby controls the mainstream media narrative and uses its financial influence to suppress Palestinian voices.", modernSource: "Protest Speech", modernYear: 2023, similarity: 0.87, tropes: ["JEWISH_CONSPIRACY"], confidence: "high" },
  { id: 4, sovietText: "Serving as the front squad of colonialism and neo-colonialism, international Zionism actively participates in the fight against national liberation movements.", sovietSource: "Great Soviet Encyclopedia", sovietYear: 1975, modernText: "Israel is a settler-colonial state built on the dispossession of indigenous Palestinians. Zionism is a tool of Western imperialism.", modernSource: "Academic Paper", modernYear: 2024, similarity: 0.86, tropes: ["ZIONISM_IMPERIALISM"], confidence: "high" },
  { id: 5, sovietText: "The Hitlerites acted in the same way when they exterminated the inferior Jewish race. Zionism-Fascism-Hitlerism.", sovietSource: "Leningradskaya Pravda / Anti-Zionist Committee", sovietYear: 1983, modernText: "What Israel is doing in Gaza is genocide — they are the new Nazis carrying out a holocaust against Palestinians.", modernSource: "Campus Protest Chant", modernYear: 2024, similarity: 0.84, tropes: ["ZIONISM_NAZISM", "BLOOD_LIBEL"], confidence: "medium" },
  { id: 6, sovietText: "We call on all Soviet citizens: workers, peasants, representatives of intelligentsia: take active part in exposing Zionism.", sovietSource: "Anti-Zionist Committee Declaration", sovietYear: 1983, modernText: "As progressives, we have a moral obligation to stand against Zionism and support the Palestinian liberation struggle through BDS.", modernSource: "Student Organization Statement", modernYear: 2024, similarity: 0.79, tropes: ["ANTI_ZIONISM_PROGRESSIVE"], confidence: "medium" },
];

const SAMPLE_TROPE_DIST = [
  { id: "ZIONISM_RACISM", name: "Zionism = Racism", sovietCount: 4, modernCount: 3 },
  { id: "ZIONISM_IMPERIALISM", name: "Zionism = Imperialism", sovietCount: 3, modernCount: 3 },
  { id: "JEWISH_CONSPIRACY", name: "Zionist Conspiracy", sovietCount: 2, modernCount: 2 },
  { id: "WEAPONIZED_ANTISEMITISM", name: "Weaponized Antisemitism", sovietCount: 2, modernCount: 2 },
  { id: "ZIONISM_NAZISM", name: "Zionism = Nazism", sovietCount: 1, modernCount: 2 },
  { id: "ANTI_ZIONISM_PROGRESSIVE", name: "Anti-Zionism as Duty", sovietCount: 1, modernCount: 1 },
  { id: "BLOOD_LIBEL", name: "Blood Libel / Atrocity", sovietCount: 1, modernCount: 1 },
  { id: "DUAL_LOYALTY", name: "Dual Loyalty", sovietCount: 1, modernCount: 0 },
  { id: "DELEGITIMIZATION", name: "Delegitimization", sovietCount: 2, modernCount: 1 },
];

const SAMPLE_TIMELINE = [
  { year: 1963, label: "Kichko: 'Judaism Without Embellishment'", type: "soviet" },
  { year: 1967, label: "Six-Day War → massive anti-Zionist campaign", type: "soviet" },
  { year: 1969, label: "Ivanov: 'Caution: Zionism!' — 800K copies", type: "soviet" },
  { year: 1975, label: "UN Resolution 3379: 'Zionism is Racism'", type: "soviet" },
  { year: 1983, label: "Anti-Zionist Committee of Soviet Public", type: "soviet" },
  { year: 1991, label: "USSR collapses; UN repeals Resolution 3379", type: "transition" },
  { year: 2001, label: "Durban Conference revives 'Zionism = Racism'", type: "modern" },
  { year: 2005, label: "BDS Movement founded", type: "modern" },
  { year: 2016, label: "Campus BDS resolutions accelerate", type: "modern" },
  { year: 2023, label: "Post-Oct 7: Soviet-era rhetoric surges", type: "modern" },
  { year: 2024, label: "Campus encampments; Soviet tropes go mainstream", type: "modern" },
];

const SAMPLE_CALIBRATION = {
  echoScores: SAMPLE_MATCHES.map(m => ({ label: m.modernSource, score: m.similarity, type: "echo" })),
  legitimateScores: [
    { label: "Policy Criticism", score: 0.31, type: "legitimate" },
    { label: "Peace Advocacy", score: 0.22, type: "legitimate" },
    { label: "Budget Discussion", score: 0.18, type: "legitimate" },
  ],
};

const DEFAULT_TROPE_NAMES = {
  ZIONISM_RACISM: "Zionism = Racism", ZIONISM_NAZISM: "Zionism = Nazism",
  ZIONISM_IMPERIALISM: "Zionism = Imperialism", JEWISH_CONSPIRACY: "Zionist Conspiracy",
  DELEGITIMIZATION: "Delegitimization", WEAPONIZED_ANTISEMITISM: "Weaponized Antisemitism",
  DUAL_LOYALTY: "Dual Loyalty", BLOOD_LIBEL: "Blood Libel / Atrocity",
  ANTI_ZIONISM_PROGRESSIVE: "Anti-Zionism as Duty",
};

const DEFAULT_TROPE_COLORS = {
  ZIONISM_RACISM: "#c0392b", ZIONISM_NAZISM: "#8e44ad", ZIONISM_IMPERIALISM: "#2980b9",
  JEWISH_CONSPIRACY: "#d35400", DELEGITIMIZATION: "#27ae60", WEAPONIZED_ANTISEMITISM: "#f39c12",
  DUAL_LOYALTY: "#1abc9c", BLOOD_LIBEL: "#e74c3c", ANTI_ZIONISM_PROGRESSIVE: "#3498db",
};

const TROPE_SHORT_LABELS = {
  ZIONISM_RACISM: "Racism",
  ZIONISM_NAZISM: "Nazism",
  ZIONISM_IMPERIALISM: "Imperialism",
  JEWISH_CONSPIRACY: "Conspiracy",
  DELEGITIMIZATION: "Delegitimize",
  WEAPONIZED_ANTISEMITISM: "Weaponized AS",
  DUAL_LOYALTY: "Dual Loyalty",
  BLOOD_LIBEL: "Blood Libel",
  ANTI_ZIONISM_PROGRESSIVE: "Progressive",
};

const TROPE_DESCRIPTIONS = {
  ZIONISM_RACISM: "Zionism as inherently racist ideology; apartheid comparisons",
  ZIONISM_NAZISM: "Zionist-Nazi collaboration; Israel employs Nazi methods",
  ZIONISM_IMPERIALISM: "Israel as tool of Western imperialism; settler-colonial framing",
  JEWISH_CONSPIRACY: "Zionist control of media, finance, governments",
  DELEGITIMIZATION: "Denial of Jewish nationhood; 'Zionist entity'",
  WEAPONIZED_ANTISEMITISM: "Dismissing antisemitism accusations as Zionist tricks",
  DUAL_LOYALTY: "Jews as agents of foreign power; conflation with Israel",
  BLOOD_LIBEL: "Accusations of deliberate child killing; dehumanization",
  ANTI_ZIONISM_PROGRESSIVE: "Opposition to Zionism framed as anti-racist/progressive duty",
};

// ============================================================
// HELPER — resolve data from pipeline JSON or fallback to samples
// ============================================================

function useResolvedData() {
  const { data: pipelineData, loading, error } = useVizData();

  const resolved = {
    matches: pipelineData?.matches ?? SAMPLE_MATCHES,
    tropeDistribution: pipelineData?.tropeDistribution ?? SAMPLE_TROPE_DIST,
    timeline: pipelineData?.timeline ?? SAMPLE_TIMELINE,
    calibration: pipelineData?.calibration ?? SAMPLE_CALIBRATION,
    tropeNames: pipelineData?.metadata?.tropeNames ?? DEFAULT_TROPE_NAMES,
    tropeColors: pipelineData?.metadata?.tropeColors ?? DEFAULT_TROPE_COLORS,
    isLive: !!pipelineData,
    loading,
    model: pipelineData?.model ?? null,
    generatedAt: pipelineData?.generated_at ?? null,
    sovietCorpusSize: pipelineData?.soviet_corpus_size ?? null,
    modernCorpusSize: pipelineData?.modern_corpus_size ?? null,
  };

  return resolved;
}

// ============================================================
// SUB-COMPONENTS
// ============================================================

function ConfidenceBadge({ level }) {
  const s = { high: { bg: "#1a472a", bd: "#2ecc71", c: "#2ecc71" }, medium: { bg: "#4a3800", bd: "#f1c40f", c: "#f1c40f" }, low: { bg: "#4a1a1a", bd: "#e74c3c", c: "#e74c3c" } }[level] || { bg: "#333", bd: "#888", c: "#888" };
  return <span style={{ background: s.bg, border: `1px solid ${s.bd}`, color: s.c, padding: "2px 8px", borderRadius: 4, fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: 1 }}>{level}</span>;
}

function SimilarityBar({ score }) {
  const pct = Math.round(score * 100);
  const color = score >= 0.85 ? "#2ecc71" : score >= 0.70 ? "#f1c40f" : score >= 0.55 ? "#e67e22" : "#555";
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
      <div style={{ flex: 1, height: 6, background: "var(--bg-card-alt)", borderRadius: 3, overflow: "hidden" }}>
        <div style={{ width: `${pct}%`, height: "100%", background: color, borderRadius: 3, transition: "width 1s ease-out" }} />
      </div>
      <span style={{ fontSize: 13, fontWeight: 700, color, minWidth: 40, textAlign: "right" }}>{pct}%</span>
    </div>
  );
}

function ScoreDonut({ score, size = 44 }) {
  const pct = Math.round(score * 100);
  const color = score >= 0.70 ? "#2ecc71" : score >= 0.55 ? "#f1c40f" : "#e67e22";
  const inner = size - 8;
  return (
    <div style={{ width: size, height: size, borderRadius: "50%", background: `conic-gradient(${color} ${score * 360}deg, var(--bg-card-alt) 0deg)`, display: "flex", alignItems: "center", justifyContent: "center" }}>
      <div style={{ width: inner, height: inner, borderRadius: "50%", background: "var(--bg-card)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 700, color: "var(--text-heading)" }}>
        {pct}%
      </div>
    </div>
  );
}

function TropeBadge({ trope, tropeNames, tropeColors }) {
  return (
    <span style={{
      background: (tropeColors[trope] || "#888") + "22",
      border: `1px solid ${(tropeColors[trope] || "#888")}55`,
      color: tropeColors[trope] || "#888",
      padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 600,
    }}>
      {tropeNames[trope] || trope}
    </span>
  );
}

function matchExplanation(match, tropeNames) {
  const tropes = match.tropes || [];
  if (tropes.length === 0) return "Both texts use strikingly similar framing when discussing Zionism and Israel.";
  const names = tropes.map(t => tropeNames[t] || t).slice(0, 2);
  const tropeStr = names.join(" and ");
  const yearGap = (match.modernYear || 2024) - (match.sovietYear || 1970);
  return `Both texts employ the "${tropeStr}" framing — the same rhetorical strategy used ${yearGap} years apart.`;
}

function MatchCard({ match, index, tropeNames, tropeColors }) {
  const [expanded, setExpanded] = useState(false);
  return (
    <div style={{
      background: "var(--gradient-card)",
      border: "1px solid var(--border)", borderRadius: 12, padding: 24,
      animation: `fadeSlideIn 0.5s ease-out ${index * 0.12}s both`,
    }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16, flexWrap: "wrap", gap: 8 }}>
        <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }}>
          <ConfidenceBadge level={match.confidence} />
          {match.tropes.map(t => <TropeBadge key={t} trope={t} tropeNames={tropeNames} tropeColors={tropeColors} />)}
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 60px 1fr", gap: 16, marginBottom: 16 }}>
        <div>
          <div style={{ fontSize: 10, textTransform: "uppercase", letterSpacing: 2, color: "#c0392b", fontWeight: 700, marginBottom: 8 }}>
            THEN — {match.sovietYear}
          </div>
          <div style={{ fontFamily: "'Georgia', serif", fontSize: 15, lineHeight: 1.6, color: "var(--text-primary)", fontStyle: "italic", borderLeft: "3px solid #c0392b", paddingLeft: 16 }}>
            "{match.sovietText}"
          </div>
          <div style={{ fontSize: 11, color: "var(--text-source)", marginTop: 8 }}>— {match.sovietSource}</div>
        </div>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "center" }}>
          <ScoreDonut score={match.similarity} />
        </div>
        <div>
          <div style={{ fontSize: 10, textTransform: "uppercase", letterSpacing: 2, color: "#3498db", fontWeight: 700, marginBottom: 8 }}>
            NOW — {match.modernYear}
          </div>
          <div style={{ fontFamily: "'Georgia', serif", fontSize: 15, lineHeight: 1.6, color: "var(--text-primary)", fontStyle: "italic", borderLeft: "3px solid #3498db", paddingLeft: 16 }}>
            "{match.modernText}"
          </div>
          <div style={{ fontSize: 11, color: "var(--text-source)", marginTop: 8 }}>— {match.modernSource}</div>
        </div>
      </div>

      <div style={{ fontSize: 12, color: "var(--text-secondary)", fontStyle: "italic", padding: "8px 0", borderTop: "1px solid var(--bg-card-alt)" }}>
        {match.echo_explanation || matchExplanation(match, tropeNames)}
      </div>

      {match.alternateMatches?.length > 0 && (
        <div style={{ marginTop: 12 }}>
          <button onClick={() => setExpanded(!expanded)} style={{
            background: "none", border: "1px solid var(--border)", color: "var(--text-secondary)", padding: "4px 12px",
            borderRadius: 6, cursor: "pointer", fontSize: 11, fontFamily: "inherit",
          }}>
            {expanded ? "Hide" : "Show"} {match.alternateMatches.length} more Soviet matches
          </button>
          {expanded && (
            <div style={{ marginTop: 8, paddingLeft: 16, borderLeft: "1px solid var(--border)" }}>
              {match.alternateMatches.map((alt, i) => (
                <div key={i} style={{ marginBottom: 8, fontSize: 12, color: "var(--text-secondary)" }}>
                  <span style={{ color: "#c0392b", fontWeight: 600 }}>{Math.round(alt.similarity * 100)}%</span>
                  {" "}&mdash; "{alt.sovietText.slice(0, 120)}..."
                  <span style={{ color: "var(--text-muted)" }}> ({alt.sovietSource}, {alt.sovietYear})</span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ============================================================
// LIVE ANALYZER — calls the FastAPI backend
// ============================================================

function LiveAnalyzer({ tropeNames, tropeColors }) {
  const [input, setInput] = useState("");
  const [results, setResults] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [apiUrl, setApiUrl] = useState("");

  const analyze = useCallback(async () => {
    if (!input.trim()) return;
    setLoading(true);
    setError(null);
    try {
      const resp = await fetch(`${apiUrl}/api/analyze`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: input, top_k: 5 }),
      });
      if (!resp.ok) throw new Error(`API returned ${resp.status}`);
      const data = await resp.json();
      setResults(data);
    } catch (e) {
      setError("Could not reach the API. Start it with: python generate_viz_data.py --serve");
    }
    setLoading(false);
  }, [input, apiUrl]);

  return (
    <div>
      <div style={{ fontSize: 12, color: "var(--text-secondary)", marginBottom: 16 }}>
        Paste any text to check for Soviet propaganda echoes. Requires the API server running locally.
      </div>

      <textarea
        value={input} onChange={e => setInput(e.target.value)}
        placeholder="Paste text here to analyze for Soviet propaganda echoes..."
        rows={4}
        style={{
          width: "100%", background: "var(--bg-input)", border: "1px solid var(--border)", color: "var(--text-primary)",
          padding: 16, borderRadius: 8, fontSize: 14, fontFamily: "'Georgia', serif",
          lineHeight: 1.6, resize: "vertical", boxSizing: "border-box",
        }}
      />

      <button onClick={analyze} disabled={loading || !input.trim()} style={{
        background: loading ? "#333" : "#c0392b", color: "#fff", border: "none",
        padding: "10px 24px", borderRadius: 6, cursor: loading ? "wait" : "pointer",
        fontSize: 13, fontWeight: 700, fontFamily: "inherit", marginTop: 8,
        letterSpacing: 1, textTransform: "uppercase", opacity: !input.trim() ? 0.4 : 1,
      }}>
        {loading ? "Analyzing..." : "Analyze Text"}
      </button>

      {error && (
        <div style={{ marginTop: 16, padding: 16, background: "#1a1010", border: "1px solid #4a2020", borderRadius: 8, color: "#e74c3c", fontSize: 12 }}>
          {error}
        </div>
      )}

      {results && (
        <div style={{ marginTop: 20 }}>
          <div style={{
            background: results.is_propaganda_derived ? "linear-gradient(135deg, #1a0d0d 0%, #2e1a1a 100%)" : "linear-gradient(135deg, #0d1a0d 0%, #1a2e1a 100%)",
            border: `1px solid ${results.is_propaganda_derived ? "#4a2020" : "#204a20"}`,
            borderRadius: 8, padding: 16, marginBottom: 16,
          }}>
            <div style={{ fontSize: 13, color: results.is_propaganda_derived ? "#e74c3c" : "#2ecc71", fontWeight: 700, marginBottom: 8 }}>
              {results.is_propaganda_derived ? "⚠ Soviet Propaganda Echo Detected" : "✓ No Significant Propaganda Match"}
            </div>
            <div style={{ fontSize: 12, color: "var(--text-primary)", lineHeight: 1.6 }}>{results.summary}</div>
          </div>

          {results.tropes_detected.length > 0 && (
            <div style={{ marginBottom: 16 }}>
              <div style={{ fontSize: 11, color: "var(--text-secondary)", marginBottom: 6 }}>Tropes detected:</div>
              <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
                {results.tropes_detected.map(t => (
                  <TropeBadge key={t.trope} trope={t.trope} tropeNames={tropeNames} tropeColors={tropeColors} />
                ))}
              </div>
            </div>
          )}

          {results.matches.map((match, i) => (
            <div key={i} style={{
              background: "var(--gradient-card)",
              border: "1px solid var(--border)", borderRadius: 8, padding: 16, marginBottom: 12,
            }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
                <ConfidenceBadge level={match.confidence} />
                <ScoreDonut score={match.similarity} size={36} />
              </div>
              <div style={{ fontSize: 10, textTransform: "uppercase", letterSpacing: 2, color: "#c0392b", fontWeight: 700, marginBottom: 4 }}>
                Soviet Source — {match.sovietYear}
              </div>
              <div style={{ fontFamily: "'Georgia', serif", fontSize: 14, color: "var(--text-primary)", fontStyle: "italic", borderLeft: "3px solid #c0392b", paddingLeft: 12, lineHeight: 1.5 }}>
                "{match.sovietText}"
              </div>
              <div style={{ fontSize: 11, color: "var(--text-source)", marginTop: 4 }}>— {match.sovietSource}</div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ============================================================
// TAB VIEWS
// ============================================================

function TimelineView({ timeline }) {
  return (
    <div style={{ position: "relative", padding: "20px 0" }}>
      <div style={{ position: "absolute", left: "50%", top: 0, bottom: 0, width: 2, background: "linear-gradient(to bottom, #c0392b, #666, #3498db)" }} />
      {timeline.map((evt, i) => {
        const isLeft = evt.type === "soviet" || evt.type === "transition";
        const color = evt.type === "soviet" ? "#c0392b" : evt.type === "transition" ? "#f1c40f" : "#3498db";
        return (
          <div key={i} style={{ display: "flex", alignItems: "center", marginBottom: 12, flexDirection: isLeft ? "row" : "row-reverse" }}>
            <div style={{ flex: 1, textAlign: isLeft ? "right" : "left", paddingRight: isLeft ? 24 : 0, paddingLeft: isLeft ? 0 : 24 }}>
              <span style={{ fontSize: 12, fontWeight: 700, color }}>{evt.year}</span>
              <span style={{ fontSize: 12, color: "var(--text-secondary)", marginLeft: 8 }}>{evt.label}</span>
            </div>
            <div style={{ width: 12, height: 12, borderRadius: "50%", background: color, border: "2px solid var(--bg-card)", zIndex: 1, flexShrink: 0 }} />
            <div style={{ flex: 1 }} />
          </div>
        );
      })}
    </div>
  );
}

function TropeChart({ tropeDistribution }) {
  const chartData = tropeDistribution
    .filter(d => d.sovietCount > 0 || d.modernCount > 0)
    .map(d => ({
      ...d,
      shortLabel: TROPE_SHORT_LABELS[d.id] || d.name,
    }));

  // Show all 9 tropes if available; ensure enough height per bar
  const barHeight = 44;
  const chartHeight = Math.max(300, chartData.length * barHeight + 60);

  const CustomTooltip = ({ active, payload }) => {
    if (!active || !payload?.length) return null;
    return (
      <div style={{ background: "var(--bg-card-alt)", border: "1px solid var(--border)", borderRadius: 8, padding: "10px 14px", fontSize: 12, color: "var(--text-primary)", maxWidth: 280 }}>
        <div style={{ fontWeight: 700, marginBottom: 4, color: "var(--text-heading)" }}>
          {payload[0]?.payload?.name}
        </div>
        <div style={{ display: "flex", justifyContent: "space-between", gap: 16, marginTop: 2 }}>
          <span style={{ color: "#c0392b" }}>Soviet (THEN)</span>
          <span style={{ fontWeight: 700 }}>{payload[0]?.value || 0}</span>
        </div>
        <div style={{ display: "flex", justifyContent: "space-between", gap: 16, marginTop: 2 }}>
          <span style={{ color: "#3498db" }}>Modern (NOW)</span>
          <span style={{ fontWeight: 700 }}>{payload[1]?.value || 0}</span>
        </div>
      </div>
    );
  };

  return (
    <>
    <ResponsiveContainer width="100%" height={chartHeight}>
      <BarChart data={chartData} layout="vertical" margin={{ left: 10, right: 20, top: 10, bottom: 10 }}>
        <XAxis type="number" tick={{ fill: "var(--text-secondary)", fontSize: 11 }} allowDecimals={false} />
        <YAxis type="category" dataKey="shortLabel" width={120} tick={{ fill: "var(--text-primary)", fontSize: 12, fontWeight: 500 }} />
        <Tooltip content={<CustomTooltip />} />
        <Bar dataKey="sovietCount" name="Soviet (THEN)" fill="#c0392b" radius={[0, 4, 4, 0]} barSize={14} />
        <Bar dataKey="modernCount" name="Modern (NOW)" fill="#3498db" radius={[0, 4, 4, 0]} barSize={14} />
      </BarChart>
    </ResponsiveContainer>
    <div style={{ display: "flex", justifyContent: "center", gap: 24, marginTop: 8, fontSize: 12 }}>
      <span style={{ display: "flex", alignItems: "center", gap: 6 }}>
        <span style={{ width: 12, height: 12, borderRadius: 2, background: "#c0392b", display: "inline-block" }} />
        <span style={{ color: "#c0392b", fontWeight: 600 }}>Soviet (THEN)</span>
      </span>
      <span style={{ display: "flex", alignItems: "center", gap: 6 }}>
        <span style={{ width: 12, height: 12, borderRadius: 2, background: "#3498db", display: "inline-block" }} />
        <span style={{ color: "#3498db", fontWeight: 600 }}>Modern (NOW)</span>
      </span>
    </div>
    </>
  );
}

function TropeDescriptionTable({ tropeNames }) {
  const allTropes = Object.keys(TROPE_DESCRIPTIONS);
  return (
    <div style={{ marginTop: 28 }}>
      <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text-primary)", marginBottom: 12, letterSpacing: 1, textTransform: "uppercase" }}>
        Trope Taxonomy
      </div>
      <div style={{ display: "grid", gap: 8 }}>
        {allTropes.map(id => (
          <div key={id} style={{
            display: "flex", gap: 12, alignItems: "flex-start",
            padding: "8px 12px", background: "var(--bg-card)", borderRadius: 8,
            borderLeft: "3px solid var(--text-muted)",
          }}>
            <div style={{ minWidth: 130 }}>
              <span style={{ fontSize: 11, fontWeight: 700, color: "var(--text-primary)" }}>
                {TROPE_SHORT_LABELS[id] || id}
              </span>
            </div>
            <div style={{ fontSize: 11, color: "var(--text-secondary)", lineHeight: 1.5 }}>
              <span style={{ color: "var(--text-primary)", fontWeight: 600 }}>{tropeNames[id] || id}</span>
              {" — "}{TROPE_DESCRIPTIONS[id]}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function CalibrationView({ calibration }) {
  const allScores = [
    ...calibration.echoScores.slice(0, 8),
    ...calibration.legitimateScores,
  ].sort((a, b) => b.score - a.score);

  return (
    <div>
      <div style={{ display: "flex", gap: 4, marginBottom: 12, flexWrap: "wrap" }}>
        {[{ label: "HIGH ≥0.85", color: "#2ecc71" }, { label: "MEDIUM ≥0.70", color: "#f1c40f" }, { label: "LOW ≥0.55", color: "#e67e22" }, { label: "NO MATCH <0.55", color: "#555" }].map(t => (
          <span key={t.label} style={{ fontSize: 10, color: t.color, fontWeight: 600, padding: "2px 6px", border: `1px solid ${t.color}33`, borderRadius: 4 }}>{t.label}</span>
        ))}
      </div>
      {allScores.map((item, i) => {
        const color = item.score >= 0.85 ? "#2ecc71" : item.score >= 0.70 ? "#f1c40f" : item.score >= 0.55 ? "#e67e22" : "#555";
        const isLegit = item.type === "legitimate";
        return (
          <div key={i} style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 6 }}>
            <span style={{ fontSize: 11, color: isLegit ? "#2ecc71" : "var(--text-primary)", minWidth: 150, textAlign: "right", fontWeight: isLegit ? 700 : 400 }}>
              {isLegit ? "✓ " : ""}{item.label}
            </span>
            <div style={{ flex: 1, height: 8, background: "var(--bg-card-alt)", borderRadius: 4, overflow: "hidden" }}>
              <div style={{ width: `${item.score * 100}%`, height: "100%", background: isLegit ? "#27ae6055" : color, borderRadius: 4 }} />
            </div>
            <span style={{ fontSize: 12, fontWeight: 700, color, minWidth: 36, textAlign: "right" }}>{Math.round(item.score * 100)}%</span>
          </div>
        );
      })}
      <div style={{ fontSize: 11, color: "#27ae60", marginTop: 16, fontStyle: "italic" }}>
        ✓ Legitimate criticism correctly scores well below threshold — no false positives
      </div>
    </div>
  );
}

function SocialCard({ match, tropeNames, tropeColors }) {
  return (
    <div style={{ background: "var(--bg-page)", border: "1px solid var(--border)", borderRadius: 16, padding: 24, maxWidth: 500, margin: "0 auto" }}>
      <div style={{ fontSize: 10, letterSpacing: 3, color: "var(--text-secondary)", textTransform: "uppercase", textAlign: "center", marginBottom: 20 }}>#IveSeenThisBefore</div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 }}>
        <div>
          <div style={{ fontSize: 10, fontWeight: 700, color: "#c0392b", letterSpacing: 2, marginBottom: 8 }}>THEN — {match.sovietYear}</div>
          <div style={{ fontSize: 14, color: "var(--text-primary)", fontStyle: "italic", lineHeight: 1.5, borderLeft: "2px solid #c0392b", paddingLeft: 12 }}>"{match.sovietText}"</div>
          <div style={{ fontSize: 10, color: "var(--text-source)", marginTop: 8 }}>{match.sovietSource}</div>
        </div>
        <div>
          <div style={{ fontSize: 10, fontWeight: 700, color: "#3498db", letterSpacing: 2, marginBottom: 8 }}>NOW — {match.modernYear}</div>
          <div style={{ fontSize: 14, color: "var(--text-primary)", fontStyle: "italic", lineHeight: 1.5, borderLeft: "2px solid #3498db", paddingLeft: 12 }}>"{match.modernText}"</div>
          <div style={{ fontSize: 10, color: "var(--text-source)", marginTop: 8 }}>{match.modernSource}</div>
        </div>
      </div>
      {match.echo_explanation && (
        <div style={{ fontSize: 12, color: "var(--text-secondary)", fontStyle: "italic", textAlign: "center", marginTop: 16, padding: "0 12px" }}>
          {match.echo_explanation}
        </div>
      )}
      <div style={{ display: "flex", gap: 6, justifyContent: "center", marginTop: 12, flexWrap: "wrap" }}>
        {match.tropes.map(t => <TropeBadge key={t} trope={t} tropeNames={tropeNames} tropeColors={tropeColors} />)}
      </div>
    </div>
  );
}

// ============================================================
// MAIN APP
// ============================================================

const TABS = ["Matches", "Analyzer", "Timeline", "Tropes", "Calibration", "Social Cards"];

export default function App() {
  const { matches, tropeDistribution, timeline, calibration, tropeNames, tropeColors, isLive, loading, model, generatedAt, sovietCorpusSize, modernCorpusSize } = useResolvedData();
  const [activeTab, setActiveTab] = useState(0);
  const [selectedCard, setSelectedCard] = useState(0);

  if (loading) {
    return (
      <div style={{ minHeight: "100vh", background: "var(--bg-page)", color: "var(--text-secondary)", fontFamily: "'Courier New', 'Consolas', monospace", display: "flex", alignItems: "center", justifyContent: "center" }}>
        <div style={{ textAlign: "center" }}>
          <div style={{ fontSize: 24, marginBottom: 12, color: "#c0392b" }}>Loading...</div>
          <div style={{ fontSize: 12, color: "var(--text-muted)" }}>Fetching visualization data</div>
        </div>
      </div>
    );
  }

  return (
    <div style={{ minHeight: "100vh", background: "var(--bg-page)", color: "var(--text-primary)", fontFamily: "'Courier New', 'Consolas', monospace", padding: "32px 24px" }}>
      <style>{`
        @keyframes fadeSlideIn { from { opacity: 0; transform: translateY(16px); } to { opacity: 1; transform: translateY(0); } }
      `}</style>
      <div style={{ maxWidth: 900, margin: "0 auto" }}>
        {/* Header */}
        <div style={{ textAlign: "center", marginBottom: 40 }}>
          <div style={{ fontSize: 11, letterSpacing: 6, color: "#c0392b", textTransform: "uppercase", marginBottom: 8 }}>
            {isLive ? "Live Data" : "Sample Data"}{model ? ` • ${model.split("/").pop()}` : ""}
          </div>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 12 }}>
            <h1 style={{ fontSize: 32, fontWeight: 300, color: "var(--text-heading)", margin: 0, fontFamily: "'Georgia', serif", letterSpacing: 1 }}>
              I've Seen This Before
            </h1>
            <ThemeToggle />
          </div>
          <p style={{ fontSize: 13, color: "var(--text-secondary)", maxWidth: 600, margin: "12px auto 0", lineHeight: 1.6 }}>
            Mapping Soviet anti-Zionist propaganda to its modern echoes using semantic similarity
          </p>
          {!isLive && (
            <div style={{ fontSize: 10, color: "#d35400", marginTop: 8 }}>
              Using sample data. Run <code style={{ background: "var(--bg-card-alt)", padding: "2px 6px", borderRadius: 3 }}>python generate_viz_data.py --generate</code> to use real embeddings.
            </div>
          )}
          {generatedAt && (
            <div style={{ fontSize: 10, color: "var(--text-muted)", marginTop: 4 }}>
              Generated: {new Date(generatedAt).toLocaleString()}
            </div>
          )}
        </div>

        {/* Tabs */}
        <div style={{ display: "flex", gap: 2, marginBottom: 32, borderBottom: "1px solid var(--bg-card-alt)", paddingBottom: 1, overflowX: "auto" }}>
          {TABS.map((tab, i) => (
            <button key={tab} onClick={() => setActiveTab(i)} style={{
              background: activeTab === i ? "var(--bg-card-alt)" : "transparent", border: "none",
              color: activeTab === i ? "var(--text-heading)" : "var(--text-source)", padding: "10px 16px", cursor: "pointer",
              fontSize: 12, fontFamily: "inherit", fontWeight: activeTab === i ? 700 : 400,
              borderRadius: "8px 8px 0 0", whiteSpace: "nowrap",
            }}>
              {tab}{tab === "Analyzer" ? " ⚡" : ""}
            </button>
          ))}
        </div>

        {/* Tab Content */}
        {activeTab === 0 && (
          <div>
            <div style={{ fontSize: 12, color: "var(--text-secondary)", marginBottom: 20, lineHeight: 1.6, maxWidth: 720, background: "var(--bg-card)", padding: "12px 16px", borderRadius: 8, borderLeft: "3px solid var(--text-muted)" }}>
              <strong style={{ color: "var(--text-primary)" }}>About these matches:</strong> Each pair shows a Soviet propaganda passage alongside modern rhetoric that uses strikingly similar framing. These are <em>structural parallels</em> in argumentation — they do not by themselves prove that modern speakers learned these arguments from Soviet sources. Establishing actual transmission pathways requires historical evidence beyond computational analysis. Matches were selected from {matches.length > 0 ? "a larger candidate set" : "automated results"} and reviewed for rhetorical coherence.
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
              {matches.map((match, i) => (
                <MatchCard key={match.id || i} match={match} index={i} tropeNames={tropeNames} tropeColors={tropeColors} />
              ))}
            </div>
          </div>
        )}

        {activeTab === 1 && (
          <div style={{ background: "var(--gradient-card)", border: "1px solid var(--border)", borderRadius: 12, padding: 24 }}>
            <LiveAnalyzer tropeNames={tropeNames} tropeColors={tropeColors} />
          </div>
        )}

        {activeTab === 2 && (
          <div style={{ background: "var(--gradient-card)", border: "1px solid var(--border)", borderRadius: 12, padding: 24 }}>
            <div style={{ fontSize: 12, color: "var(--text-secondary)", marginBottom: 16 }}>The pipeline from Soviet propaganda factories to modern campus discourse</div>
            <TimelineView timeline={timeline} />
          </div>
        )}

        {activeTab === 3 && (
          <div style={{ background: "var(--gradient-card)", border: "1px solid var(--border)", borderRadius: 12, padding: 24 }}>
            <div style={{ fontSize: 12, color: "var(--text-secondary)", marginBottom: 16 }}>Which Soviet propaganda tropes appear most frequently in modern discourse</div>
            <TropeChart tropeDistribution={tropeDistribution} />
            <TropeDescriptionTable tropeNames={tropeNames} />
          </div>
        )}

        {activeTab === 4 && (
          <div style={{ background: "var(--gradient-card)", border: "1px solid var(--border)", borderRadius: 12, padding: 24 }}>
            <div style={{ fontSize: 12, color: "var(--text-secondary)", marginBottom: 16 }}>Confidence calibration — legitimate criticism scores well below match threshold</div>
            <CalibrationView calibration={calibration} />
          </div>
        )}

        {activeTab === 5 && (
          <div>
            <div style={{ fontSize: 12, color: "var(--text-secondary)", marginBottom: 16 }}>Shareable cards for the #IveSeenThisBefore campaign</div>
            <div style={{ display: "flex", gap: 8, marginBottom: 20, justifyContent: "center", flexWrap: "wrap" }}>
              {matches.map((_, i) => (
                <button key={i} onClick={() => setSelectedCard(i)} style={{
                  background: selectedCard === i ? "var(--border)" : "transparent",
                  border: `1px solid ${selectedCard === i ? "#3498db" : "var(--border)"}`,
                  color: selectedCard === i ? "var(--text-heading)" : "var(--text-secondary)", padding: "6px 12px",
                  borderRadius: 6, cursor: "pointer", fontSize: 11, fontFamily: "inherit",
                }}>
                  Match {i + 1}
                </button>
              ))}
            </div>
            {matches[selectedCard] && <SocialCard match={matches[selectedCard]} tropeNames={tropeNames} tropeColors={tropeColors} />}
          </div>
        )}

        {/* Dataset Info Bar */}
        <div style={{
          display: "flex", justifyContent: "center", gap: 24, marginTop: 48, padding: "12px 16px",
          background: "var(--bg-card)", border: "1px solid var(--bg-card-alt)", borderRadius: 8, flexWrap: "wrap",
        }}>
          {sovietCorpusSize != null && (
            <span style={{ fontSize: 11, color: "#c0392b" }}>Soviet Corpus: <strong>{sovietCorpusSize}</strong> passages</span>
          )}
          {modernCorpusSize != null && (
            <span style={{ fontSize: 11, color: "#3498db" }}>Modern Corpus: <strong>{modernCorpusSize}</strong> passages</span>
          )}
          <span style={{ fontSize: 11, color: "var(--text-secondary)" }}>Matches: <strong style={{ color: "var(--text-primary)" }}>{matches.length}</strong></span>
          {model && (
            <span style={{ fontSize: 11, color: "var(--text-secondary)" }}>Model: <strong style={{ color: "var(--text-primary)" }}>{model.split("/").pop()}</strong></span>
          )}
        </div>

        {/* Footer */}
        <div style={{ textAlign: "center", marginTop: 16, paddingTop: 24, borderTop: "1px solid var(--bg-card-alt)" }}>
          <div style={{ fontSize: 10, color: "var(--text-muted)", letterSpacing: 2 }}>
            {isLive ? "LIVE DATA FROM ML PIPELINE" : "PROTOTYPE — SAMPLE DATA"} • SIMILARITY SCORES {isLive ? "COMPUTED BY" : "WILL BE COMPUTED BY"} EMBEDDING MODEL
          </div>
        </div>
      </div>
    </div>
  );
}
